### ISSUE TITLE
Create documentation for centerPiece() function.

### ISSUE THREAD

**Issue by LSaber36** [ucfai/knightros-gambit#130]

**Comment by LSaber36** [comment]
This documentation is for the code in issues #114 and #87

**Comment by LSaber36** [comment]
This should be placed in the [Project Overview Doc](https://docs.google.com/document/d/1CPY9yEVWDVO99mbckBnCJi-gKKobkBnB4XnjrLc4HFs/edit#)

**Comment by nashirj** [comment]
The final version is in a standalone doc [here](https://docs.google.com/document/d/1qPVzmNZ1SlqHGRc4QSPqd3QUV_wz1zTZZDX9lXvBuHw/edit) and has also been included in the Project Overview Doc [here](https://docs.google.com/document/d/1CPY9yEVWDVO99mbckBnCJi-gKKobkBnB4XnjrLc4HFs/edit#heading=h.xgsqpi4kjk8e)
