### ISSUE TITLE
Make project webpage

### ISSUE THREAD

**Issue by nashirj** [ucfai/knightros-gambit#5]
Something like this: https://stanfordstudentrobotics.org/pupper

Could have UCF AI link to our project page on this page: https://ucfai.org/groups/projects/
Could have UCF IEEE link to our project page on this page: https://ieee.cecs.ucf.edu/projects/

**Comment by nashirj** [comment]
Things we could include on the website right now:
1) CAD of the board design
2) Electrical schematic
3) Link to this github repo
4) Diagrams showing code structure?
5) Information about the project
6) Member info

**Comment by nashirj** [comment]
Reference http://www.raspberryturk.com/, would be cool to eventually have something like that

**Comment by RuthShryock** [comment]
I used Figma to make a prototype and here is the link: https://www.figma.com/file/MXUHeaBronQ7sH9lyn8tcR/KGWebsite?node-id=0%3A1

**Comment by nashirj** [comment]
We will be making the project webpage in [this repository](https://github.com/ucfai/knightr0s-gambit-website).

**Comment by nashirj** [comment]
I lied, we'll be making it in this repository in the /docs folder and using Jekyll (like Raspberry Turk)
