### ISSUE TITLE
Add positive extreme endstops and move tracking out of movement loops

### ISSUE THREAD

**Issue by nashirj** [ucfai/knightros-gambit#73]
Need to account for only having one end stop in code by virtually tracking the side of the axis that doesn't have an end stop.

**Comment by LSaber36** [comment]
Can only be completed when issue #88 is completed

**Comment by LSaber36** [comment]
Update: Need to add new endstops to the code. This includes new pins, pin initializations, and checks in the for loops.

**Comment by LSaber36** [comment]
We also need to update the homeAxis() function to account for the new conditions and set currentX and currentY accordingly

**Comment by LSaber36** [comment]
- We need to add new endstops to the code. This includes new pins, pin initializations, and checks in the for loops
- We also need to update the homeAxis() function to account for the new conditions and set currentX and currentY accordingly
- We also want to move the tracking out of the loops and compute them directly, after the loop
_**These groups of things should be in their own commits to group the changes**_

**Comment by nashirj** [comment]
when you do step 4, please add a comment above the line where you call `home()` explaining that the function aligns axes and sets the currentX and currentY to zero.
