### ISSUE TITLE
Edit the movement functions to allow for easily moving half of a space

### ISSUE THREAD

**Issue by LSaber36** [ucfai/knightros-gambit#86]

**Comment by LSaber36** [comment]
This can be done by approximately doubling the board resolution (might be more like 2x +- 1 or something like that)

**Comment by LSaber36** [comment]
This should ideally be done before issues #88 and #93

**Comment by nashirj** [comment]
I think this issue should stay open until the refactor to use the new `halfspace` function and remove all the float logic is done
